### ISSUE TITLE
totalSupply()

### ISSUE THREAD

**Issue by CRYPTO-GENIK** [manifoldxyz/creator-core-solidity#4]
I can't find a totalSupply() function like in other contracts, how do you get the totalSupply with Manifold contracts?

**Comment by wwhchung** [comment]
There is no totalSupply function as it is not part of the base EIP-721 spec.  It is part of the 721 extension, and if you want on-chain enumerability, you would use:
https://github.com/manifoldxyz/creator-core-solidity/blob/main/contracts/ERC721CreatorEnumerable.sol

However, mint costs would be much more expensive due to the need to track the enumeration data.

The vast majority choose not to do this as you can get enumeration, supply and other data by observing the emitted on-chain events and using API's like those provided by our developer tools, OpenSea, Alchemy or The Graph
